### ISSUE TITLE
expr  = ce.parse("\frac{x^{n}}{a}") evaluate to constant when changing x

### ISSUE THREAD

**Issue by erramidad123** [cortex-js/compute-engine#158] opened 2024-04-01 23:10 UTC
a : integer > 1  : [2,4,5,6,7,8....] 
n : integer > 1 

exp : 
const expr = ce.parse("\frac{x}{3}");

for (const x = 0; x < 1; x += 0.01) {
  ce.assign('x', x);
  console.log(`f(${x}) = ${expr.value}`);  // this will be constant all time .
}

**Comment by arnog** [comment] 2024-04-25 19:39
It seems to work using top of tree. I believe this is a duplicate of #150.

**Closed by arnog** 2024-04-25 19:39 UTC
