### ISSUE TITLE
MathLive: a closing parentheses after a function application is ignored

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#101] opened 2023-08-25 09:52 UTC
My application has logging code and I noticed what I think is a problem with .simplify().  Here is the code, and below that are results for two expressions.  One of the expressions is missing an ending parenthesis:

              let mathLatex = mf1.getValue('latex')
              let mathJson  = mf1.getValue('math-json')
              let mfExpression = mf1.expression
              let mfNLatex = MathfieldElement.computeEngine.parse(mathLatex).N().latex
              let mfSLatex = MathfieldElement.computeEngine.parse(mathLatex).simplify().latex
              let mfELatex = MathfieldElement.computeEngine.parse(mathLatex).evaluate().latex
              MathfieldElement.computeEngine.latexOptions = { precision: 6 }
              
              mf2.setValue(mfNLatex)
              mf3.setValue(mfSLatex)
              mf4.setValue(mfELatex)
              mf5.setValue(mathJson)
 
              logToConsole("mathLatex:" + mathLatex);
              logToConsole("mfExpression:" + mfExpression);
              logToConsole("mfNLatex:" + mfNLatex);
              logToConsole("mfSLatex:" + mfSLatex);
              logToConsole("mathJson:" + mathJson)

<img width="674" alt="Screenshot 2023-08-25 at 17 47 36" src="https://github.com/cortex-js/compute-engine/assets/39233783/d4819c05-b466-46ba-bfc9-1aa16ce60f8b">

<img width="672" alt="Screenshot 2023-08-25 at 17 46 44" src="https://github.com/cortex-js/compute-engine/assets/39233783/24530026-3b4f-4de7-a85e-bf8c845cfbed">

**Comment by rs-mobitech** [comment] 2023-08-25 09:58
For reference, here's the Latex also

mfSLatex:\frac{1}{2}(\sin(1)\cos(1))

I believe the latex is correct but the mfSLatex and mfELatex are both incorrect and missing a ")" from the end

**Comment by rs-mobitech** [comment] 2023-08-25 10:45
One more example

<img width="536" alt="Screenshot 2023-08-25 at 18 44 38" src="https://github.com/cortex-js/compute-engine/assets/39233783/fa0db553-6518-4919-833f-4f5e26164a91">

**Comment by arnog** [comment] 2023-08-25 15:03
What happens if you do `mf3.setValue("\\frac{1}{2}(\\sin(1)\\cos(1))")` ?

**Comment by rs-mobitech** [comment] 2023-08-25 16:09
Here's what happens:

<img width="126" alt="Screenshot 2023-08-26 at 0 05 41" src="https://github.com/cortex-js/compute-engine/assets/39233783/f95a1141-d1fe-43b0-9d69-04e3dc94ddf7">

Then I also added a few 1s before the \\\frac and it gives me this:

<img width="188" alt="Screenshot 2023-08-26 at 0 06 37" src="https://github.com/cortex-js/compute-engine/assets/39233783/36654a12-3a63-4e4f-9e76-e07bd7016e70">

There is a lot of space and I have seen some much longer strings in that field

**Comment by rs-mobitech** [comment] 2023-08-26 13:42
Here's another example, where you can see the difference with simplify.  In MathLive, it's not able to simplify, but Nerdamer does simplify correctly.

<img width="987" alt="Screenshot 2023-08-26 at 13 33 00" src="https://github.com/cortex-js/compute-engine/assets/39233783/6a8b9d62-b4fb-49be-b483-5b1219ef6204">

**Comment by arnog** [comment] 2023-08-26 18:50
OK, so if you get the same problem when setting the LaTeX value directly, the issue is not related to Simplify.

The issue appears to be in MathLive. Entering `(f(x))` will result in the final closing parenthesis not being displayed.

**Comment by arnog** [comment] 2023-08-28 04:12
Fixed in aaf6a46172bdc4b9e4dac469bb87276c5e3d6d4c

**Closed by arnog** 2023-08-28 04:12 UTC
Labels: bug
