### ISSUE TITLE
[FEATURE] Evaluate the result of an expression in specific units

### ISSUE THREAD

**Issue by rwmorton** [cortex-js/compute-engine#140] opened 2024-01-17 17:16 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to do the computation in specific units (ie. radians or degrees).

**Describe the solution you'd like**
To be able to tell the compute engine what units you would like to use for trig functions (for example).

**Comment by arnog** [comment] 2024-01-17 20:08
I think this is a duplicate of #82.

**Comment by arnog** [comment] 2024-03-05 02:15
Not response in several weeks. Closing.

**Closed by arnog** 2024-03-05 02:15 UTC
Labels: feature
