### ISSUE TITLE
Can't init ComputeEngine using iPhone SE

### ISSUE THREAD

**Issue by truebluepl** [cortex-js/compute-engine#209] opened 2024-10-18 09:03 UTC
## Description

I can't init ComputeEngine object.

### Steps to Reproduce

`let ce = new ComputeEngine();`
via MathField object CE is not accessible also.

### Actual Result

CE 0.24.1
SyntaxError: Invalid regular expression: invalid property expression at line 3880
`var ONLY_EMOJIS = new RegExp(`^(?:${POSSIBLE_EMOJI})+$`, "u");`

CE 0.26.4
ReferenceError: Can't find variable: BigInt at line 6287
`BigInt(2),`

CE 0.24.1 and CE 0.26.4
TypeError: Object is not a constructor (evaluating 'new ComputeEngine()')
`let ce = new ComputeEngine();`

### Expected Result

CE object should be created.

### Environment

I tested using iPhone SE 2020/iOS13/Safari (at BrowserStack.com).

**Comment by arnog** [comment] 2024-10-18 14:56
The issue is probably not the iPhone SE but rather iOS 13, released in 2019.

> Obsolete, no longer receiving security updates, because all iPhones and iPod Touches that supported iOS 13 support iOS 14 and iOS 15 as well.

**Comment by arnog** [comment] 2024-12-03 15:46
No activity in over 4 weeks. Closing.

**Closed by arnog** 2024-12-03 15:46 UTC
