### ISSUE TITLE
Substitution and negative power returns wrong result

### ISSUE THREAD

**Issue by truebluepl** [cortex-js/compute-engine#159] opened 2024-04-25 07:27 UTC
## Description
Substitution of x and negative power returns wrong result.

### Steps to Reproduce
const ce = new ComputeEngine.ComputeEngine();

//x=3/7
let a = ce.parse('\\frac{x^{-1}}{9}').subs({
  x: ce.parse('\\frac{3}{7}'),
});

//x=3/7 but included in expression
let b = ce.parse('\\frac{(\\frac{3}{7})^{-1}}{9}');
console.log(a,b);

### Actual Behavior
Substitution returns 21.

### Expected Behavior
Should returns 7/27.

**Comment by arnog** [comment] 2024-04-25 16:58
I can't reproduce this. I'm getting 7/27 as the answer, as expected.

**Comment by truebluepl** [comment] 2024-04-25 17:13
Hmm... I've prepares fiddle: https://jsfiddle.net/uprwaxj7/

Here is screenshot. At bottom right corner is console output:
![image](https://github.com/cortex-js/compute-engine/assets/68942963/66d0244c-115c-491f-9cbb-8dbd5003d46d)

**Comment by arnog** [comment] 2024-04-25 19:10
OK, I think this is a duplicate of #147. I can't reproduce the problem with top of tree.

**Comment by truebluepl** [comment] 2024-04-29 07:42
I think there is a problem when the power of the numerator is exactly -1.
I made some test:

`//wrong, result=8, should be 0.5
let a = ce.parse('\\frac{x^{-1}}{4}').subs({
  x: ce.parse('0.5'),
}).N().value;
console.log(a);

//wrong, result=1, should be 0.25
let b = ce.parse('\\frac{x^{-1}}{2}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(b);

//ok
let c = ce.parse('x^{-1}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(c);

//ok
let d = ce.parse('\\frac{2}{x^{-1}}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(d);

//ok
let e = ce.parse('\\frac{x^{-2}}{x^{-1}}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(e);

//ok
let f = ce.parse('\\frac{x^{-2}}{4}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(f);

//ok
let g = ce.parse('\\frac{x^{-3}}{4}').subs({
  x: ce.parse('2'),
}).N().value;
console.log(g);`

**Comment by arnog** [comment] 2024-06-25 14:05
Verified these all work with TOT.

**Closed by arnog** 2024-06-25 14:05 UTC

**Comment by truebluepl** [comment] 2024-06-25 14:35
Hello!
What do you mean by TOT?
I prepared those examples using JSFiddle: https://jsfiddle.net/dxr6u7La/ Still with bugs...

**Comment by arnog** [comment] 2024-06-25 15:15
TOT is top of tree, the latest HEAD in github.
